@baseUrl = http://localhost:5166

### Enqueue a job
POST {{baseUrl}}/api/jobs
Content-Type: application/json

{
    "type": "SendEmail",
    "payload": "{\"to\": \"test@gmail.com\", \"subject\": \"Hello!\"}",
    "priority": 5,
    "maxRetries": 3,
    "scheduledAt": null
}