@baseUrl = http://localhost:5166

### Enqueue a job
POST {{baseUrl}}/api/jobs
Content-Type: application/json

{
    "type": "SendEmail",
    "payload": "{\"to\": \"sarthak.sharma@gmail.com\", \"subject\": \"Hello!\"}",
    "priority": 5,
    "maxRetries": 3,
    "scheduledAt": null
}

### Get a job by id
GET {{baseUrl}}/api/jobs/4d8559eb-f7eb-49a1-91c8-834de352ef32